#!/bin/bash

# Check that the versions of dcs-get are the same
# VERSION should be updated every time the bash script is edited
VERSION="2.0"
if [ ! "$1" = $VERSION ]
then
	echo "Please update to the latest version of dcs-get at http://backus.uwcs.co.uk/dcs-get/"
        exit 1
fi

# If someone else owns the directory, remove it using cleanup script
if [[ -d /var/tmp/dcs-get && ! -O /var/tmp/dcs-get ]]
then
	if [ "$(md5sum /var/tmp/dcs-get/cleanup)" == "a79206b7a10ee067912405d824875549  /var/tmp/dcs-get/cleanup" ]
	then
		/var/tmp/dcs-get/cleanup
	else
		echo "Someone has screwed with the cleanup script, hurt them."
	fi
fi

# If the directory doesn't exist create it, cleanup script and grab dcs-get client,api and server scripts.
if [ ! -d /var/tmp/dcs-get ]
then
	mkdir /var/tmp/dcs-get
	chmod a+rX /var/tmp/dcs-get
	cd /var/tmp/dcs-get
	mkdir bin
	mkdir lib
	mkdir downloads
	mkdir downloaded
	touch cleanup
	echo -e "#!/usr/bin/perl\nuse File::Path 'rmtree';\nrmtree([ '/var/tmp/dcs-get' ]);" > cleanup
	chmod a+rx cleanup
	chmod ug+s cleanup

	# Get node to execute client
	wget http://backus.uwcs.co.uk/dcs-get/packages/node-0.4.2.tar.gz
	tar zxf node-0.4.2.tar.gz
	
	#Get dcs-get scripts.
	cd bin
	wget -q http://backus.uwcs.co.uk/dcs-get/dcs-get-client
	wget -q http://backus.uwcs.co.uk/dcs-get/dcs-get-api
	wget -q http://backus.uwcs.co.uk/dcs-get/dcs-get-server
	chmod u+x dcs-get-client
	chmod u+x dcs-get-server
	./dcs-get-server
fi