#!/var/tmp/dcs-get/bin/node-0.4.2

//This is the dcs-get command line client.

var dcsGet = require( "./dcs-get-api" );
var tty = require('tty');

if (process.argv[2] === undefined) {
	console.log("Try dcs-get help");
	return;
}
else {
	switch (process.argv[2]) {
		case "list":
		case "l":
			dcsGet.listPackages();
			break;
		case "list-dev":
		case "ld":
			dcsGet.listPackagesDev();
			break;
		case "clean":
		case "c":
			dcsGet.clean();
			break;
		case "search":
		case "s":
			dcsGet.search( process.argv[3] );
			break;
		case "install":
		case "i":
			process.argv.shift();
			process.argv.shift();
			process.argv.shift();
			dcsGet.install( process.argv );
			var id = setInterval(function drawProgress() {
				dcsGet.listDownloading(function(err, packageList) {
					if (err) {
						console.log(err);
						clearInterval( id );
					}
					else {
						var n = 0;
						var totalPackageDownloaded = 0;
						var totalPackageSize = 0;

						for(package in packageList) {
							n++;
							totalPackageDownloaded += packageList[package].downloaded;
							totalPackageSize += packageList[package].totalSize;

							var fracDone = packageList[package].downloaded/packageList[package].totalSize;

							process.stdout.write("\033[K" + package + ": " + (fracDone*100).toFixed(2) + "%\n");
							drawProgressBar(fracDone);
						}
						if (n) {
							var totalFracDone = totalPackageDownloaded/totalPackageSize;
							process.stdout.write("\033[KTotal: " + ((totalPackageDownloaded/totalPackageSize)*100).toFixed(2) + "%\n\033[K");
							drawProgressBar(totalFracDone);
							process.stdout.write("\033[K\n\033[K");
							process.stdout.write("\033[" + (2*n+3) + "A");
						} else {
							clearInterval(id);
						}
					}
				});
			}, 250 );
			break;
		case "reinstall":
		case "r":
			process.argv.shift();
			process.argv.shift();
			process.argv.shift();
			dcsGet.reinstall( process.argv );
			break;			
		case "list-downloading":
			dcsGet.listDownloading( function( err, packageName, downloaded, totalSize) {
				if ( !err ) {
					process.stdout.write( packageName + ": " + (downloaded/totalSize)*100 + "%\n");
				}
			});
			break;
		case "list-installed":
		case "li":
			dcsGet.listInstalled();
			break;
		case "gensymlinks":
		case "g":
			process.argv.shift();
			process.argv.shift();
			process.argv.shift();
			dcsGet.genSymlinks( process.argv );
			break;
		case "package":
		case "p":
			process.argv.shift();
			process.argv.shift();
			process.argv.shift();
			dcsGet.package( process.argv );
			break;
		case "upload":
		case "u":
			process.argv.shift();
			process.argv.shift();
			process.argv.shift();
			dcsGet.upload( process.argv );
			break;
		case "help":
			dcsGet.help();
			break;
		case "commands":
			console.log("commands search install reinstall list list-dev clean gensymlinks package help upload");
			break;
		default:
			console.log("Try dcs-get help");
	}	
}

function drawProgressBar(fracDone)
{
	var termWidth = tty.getWindowSize()[1];

/*
	if (fracDone <= 0.25) {
		process.stdout.write('');
	} else if (fracDone <= 0.75) {
		process.stdout.write('');
	} else {
		process.stdout.write('');
	}
*/
	process.stdout.write('\033[K[');
	process.stdout.write('\033[32m'); //set foreground green
	process.stdout.write('\033[41m'); //set background red
	for (var i=0; i<(fracDone*(termWidth-3))-1; i++) {
		process.stdout.write('█');
		//process.stdout.write('=');
	}
	///*
	if ((fracDone*(termWidth-3))%1>=0.5) {
		process.stdout.write('▌');
	} else {
		process.stdout.write(' ');
	}
	//*/
	//process.stdout.write('>');
	for (var i=0; i<((1-fracDone)*(termWidth-3)); i++) {
		process.stdout.write(' ');
	}
	process.stdout.write('\033[0m');
	process.stdout.write(']\n');
}
