#!/var/tmp/dcs-get/bin/node-0.4.2

/*
This is the server that runs the package management and download processes.
We can download in parallel by spawning multiple instances of the downloadPackage function.
Keep track of downloaded packages in here, rather than downloading the JSON every time we run dcs-get.
*/

// Node modules
var http = require('http');
var fs = require('fs');
var util = require('util');
var spawn = require('child_process').spawn;
var net = require( 'net' );
var path = require( 'path' );
var crypto = require('crypto');

//Settings for our http/net connections and other things.
var settings = {
	'install_dir': '/var/tmp/dcs-get',
	'base_host': 'backus.uwcs.co.uk',
	'base_path': '/dcs-get/',
	'debug': true,
	'port': 101010
};

// Global variable for packages
var packages;

//Packages being downloaded.
var downloading = {};

//Things to ignore in readdir.
var ignore = new Array( "bin", "lib", "downloads", "downloaded", "cleanup" );

// Grab the package list from backus
http.get({
	host: settings['base_host'],
	port: 80,
	path: settings['base_path']+'packages.json'
}, function(res) {
	res.setEncoding('utf8');
	var data = '';
	res.on('data', function (chunk) {
		data += chunk;
	});
	res.on('end', function () {
		try {
			packages = JSON.parse(data);
			packages = sortObject(packages);
		} catch (e) {
			console.log("Error: Problem with package data");
			if (settings.debug) console.log(e);
			return;
		}
	});
}).on('error', function(e) {
	console.log("Error: Problem downloading package list from backus");
	if (settings.debug) console.log(e);
});

/*
Create a server that manages downloads and the JSON.
Can now keep track of downloaded packages "live" instead of reading /var/tmp/dcs-get on launch.

Listens for two commands:
INSTALL <foo> installs package foo. Dependencies are handled in the api, not here.
GETJSON returns the packages JSON to the api.
*/

var server = net.createServer( function( stream ) {
	stream.setEncoding('utf8');

	stream.on( 'data', function ( data ) {

		//For testing purposes/niceness: telnet ends with \r\n, socat with \n and we don't want tabs anyway.
		var args = data.toString().replace(/[\n,\r,\t]/,"").split(" ");
		
		switch( args[0] ) {
			case "INSTALL":
				
				//We can assume package names are well-formed.
				//No, we really can't
				var temp = args[1].match(/(.*)-(.*)/);
				if(temp)
				{
					aquirePackage(temp[1], temp[2]);
				}
				stream.end();
				break;
				
			case "GETJSON":
				
				stream.end( JSON.stringify( packages ));
				break;
			
			case "DOWNLOADING":
				
				stream.end( JSON.stringify( downloading ) );
				break;
				
			default:
				stream.end( "No such function." );
		}
	});
	stream.on('error', function(err){
		console.log(err);
	});
}).listen(settings['port'], 'localhost');

function aquirePackage(package, packageVersion) {
	downloading[package] = {
		'version': packageVersion,
		'downloaded': 0,
		'totalSize': 1
	};
	var tarPath = settings.install_dir + '/downloaded/' + package + '-' + packageVersion + '.tar.gz';
	if(path.existsSync(tarPath)) {
		install(null, package, packageVersion);
		downloading[package].downloaded = 1;
	} else {
		downloadPackage(package, packageVersion, install);
	}
}

function downloadPackage(package, packageVersion, callback) {
	http.get({
		host: settings['base_host'],
		port: 80,
		path: settings['base_path'] + 'packages/' + package + '-' + packageVersion + '.tar.gz'
	}, function(res) {
		res.on('data', function (chunk) {
			downloading[package].totalSize = Number(res.headers['content-length']);
			downloading[package].downloaded += chunk.length;
		});
		res.on('end', function () {
			fs.rename(settings.install_dir + '/downloads/' + package + '-' + packageVersion + '.tar.gz', settings.install_dir + '/downloaded/' + package + '-' + packageVersion + '.tar.gz', function ( err ) {
				callback(err, package, packageVersion);
			});
		});
		// Save file
		util.pump(res, fs.createWriteStream(settings['install_dir'] + '/downloads/' + package + '-' + packageVersion + '.tar.gz'));
	}).on('error', function(e) {
		console.log('Error: Problem downloading package.\n' + package + '-' + packageVersion);
		if (settings.debug) console.log(e);
	});
}

function install(err, package, packageVersion)
{
	var tarPath = settings.install_dir + '/downloaded/' + package + '-' + packageVersion + '.tar.gz';
	var fileHash = crypto.createHash('md5');
	var s = fs.ReadStream(tarPath);
	s.on('data',function(data) {
		fileHash.update(data);
	});
	s.on('end', function() {
		var packageHash = packages[package].md5[packageVersion];
		if (packageHash == fileHash.digest('hex')) {
			packages[package].installed = packageVersion;
			// Extract contents
			var tar = spawn('tar', ['zx','-C', settings['install_dir']]);
			var s = fs.ReadStream(tarPath);
			util.pump(s, tar.stdin);
			tar.on('exit', function() {
				console.log('Installed ' + package + '-' + packageVersion);
				packages[package].installed = 1;
				delete downloading[package];
			});
		} else {
			console.log('WARNING: ' + tarPath + ' hash incorrect: ' + packageHash);
			fs.unlink(tarPath);
			delete downloading[package];
		}
	});
}

function sortObject(o) {
	var sorted = {},
		key, a = [];

	for (key in o) {
		if (o.hasOwnProperty(key)) {
			a.push(key);
		}
	}

	a.sort();

	for (key = 0; key < a.length; key++) {
		sorted[a[key]] = o[a[key]];
	}
	return sorted;
}
